image: python:3.10

before_script:
  - python --version # For debugging
  - pip install isort pylint pytest pyqt6 db-sqlite3 requests

stages:
  - linting
  - test

isort:
  stage: linting
  script:
    - python -m isort . --check-only

pylint:
  stage: linting
  script:
    - python -m pylint src

pytest:
  stage: test
  script:
    - pytest
  only:
    - merge_request
